# backend/chat_router.py
# ─────────────────────────────────────────────────────────────────
# /api/chat endpoint
# Local-only chatbot logic for SpeechSense.
# No external OpenAI or Anthropic API keys are required.
# ─────────────────────────────────────────────────────────────────

from fastapi import APIRouter
from pydantic import BaseModel
from typing import List, Optional

router = APIRouter()

# ── Speech therapy system prompt ─────────────────────────────────
SYSTEM_PROMPT = """You are SpeechSense Assistant — a friendly, expert AI assistant embedded in a speech therapy platform for children with Speech Sound Disorders (SSDs).

You help:
- Parents and therapists understand phoneme-level errors (substitutions, omissions, insertions)
- Explain common SSD patterns like gliding (/r/→/w/), th-fronting (/θ/→/f/), fronting (/k/→/t/)
- Suggest targeted, age-appropriate practice exercises for specific phoneme errors
- Explain what Phoneme Error Rate (PER) means and how to improve it
- Guide users through the platform: Upload audio → Analyse → Feedback → Report
- Answer questions about Whisper transcription and how the AI detects errors

Tone: Friendly, encouraging, concise. Use simple language.
Format: Keep replies under 4 sentences unless a detailed explanation is asked for.
Never make clinical diagnoses. Always recommend consulting a certified SLP for formal assessment."""


# ── Request / Response schemas ────────────────────────────────────
class ChatMessage(BaseModel):
    role: str      # "user" or "assistant"
    content: str

class ChatRequest(BaseModel):
    question: str
    history: Optional[List[ChatMessage]] = []   # conversation history


def generate_local_reply(question: str) -> str:
    q = question.strip().lower()
    if not q:
        return "Please ask a question about speech analysis, target words, phoneme errors, or the practice workflow."

    if any(term in q for term in ["hello", "hi", "hey", "good morning", "good afternoon"]):
        return "Hi! I can help with speech analysis, target words, phoneme errors, and the practice workflow. Ask me anything."

    if any(term in q for term in ["target word", "target phrase", "word", "phrase"]):
        return "The target word tells the system which expected phoneme sequence to compare against. Use a clear word or phrase, then upload or record audio for analysis."

    if any(term in q for term in ["audio", "upload", "record", "file", "wav", "mp3"]):
        return "Use the app's audio upload or record controls. The backend converts your audio to WAV and detects phonemes with HuBERT."

    if any(term in q for term in ["error", "phoneme", "substitution", "omission", "insertion", "per"]):
        return "The app detects phoneme substitutions, omissions, and insertions. Focus practice on the error phonemes shown in feedback to improve quickly."

    if any(term in q for term in ["feedback", "practice", "exercise", "tts", "listen", "repeat"]):
        return "After analysis, review the feedback page for the error phonemes and practice tips. Use the listen-and-repeat prompts to rehearse the sounds."

    if any(term in q for term in ["report", "clinical", "print", "download"]):
        return "The report page summarizes accuracy, phoneme errors, and recommendations so you can track progress and share results with a therapist."

    if any(term in q for term in ["model", "huggingface", "backend", "api", "hubert", "phoneme model"]):
        return "This app uses a local HuBERT phoneme model for speech analysis and a backend chat endpoint for guidance."

    return "I can help with speech analysis, target words, phoneme practice, and how to use the app. Please ask me about those areas."


# ── /api/chat endpoint ────────────────────────────────────────────
@router.post("/api/chat")
async def chat(body: ChatRequest):
    """
    Accepts a question + optional conversation history.
    Returns a local chatbot answer generated by the model logic.
    """

    return {"answer": generate_local_reply(body.question)}
